<?php

return [
    'ezcontentobject_attribute' => [
        0 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 181,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => 'Deliver',
            'data_type_string' => 'ezstring',
            'id' => '281',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => 'deliver',
            'version' => 1,
        ],
        1 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 182,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '',
            'data_type_string' => 'ezstring',
            'id' => '282',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        2 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => 1045487555,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph>Content consumption is changing rapidly. An agile solution to distribute your content and empower your digital business model is key to success in every industry.</paragraph></section>',
            'data_type_string' => 'ezxmltext',
            'id' => '283',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        3 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 184,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => 1045487555,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph>eZ Publish Enterprise is the platform to make the omni-channel approach possible. A powerful presentation engine provides a multiplicity of websites and pages that display your content in a variety of renderings. A powerful API directly and simply integrates your content with any Web-enabled application on any device, including the iPad, iPhone or Android without ever interfering with or impacting the platform itself.</paragraph></section>',
            'data_type_string' => 'ezxmltext',
            'id' => '284',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        4 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 185,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => 1045487555,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"/>',
            'data_type_string' => 'ezstring',
            'id' => '285',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        5 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 186,
            'contentobject_id' => 68,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<?xml version="1.0" encoding="utf-8"?>
<ezimage serial_number="1" is_valid="1" filename="Deliver.jpg" suffix="jpg" basename="Deliver" dirpath="var/ezdemo_site/storage/images/getting-started/selected-features/deliver/286-1-eng-GB" url="var/ezdemo_site/storage/images/getting-started/selected-features/deliver/286-1-eng-GB/Deliver.jpg" original_filename="c97d7955.jpg" mime_type="image/jpeg" width="770" height="281" alternative_text="" alias_key="1293033771" timestamp="1522944959"><original attribute_id="286" attribute_version="1" attribute_language="eng-GB"/><information Height="281" Width="770" IsColor="1" ByteOrderMotorola="1" Thumbnail.FileType="2" Thumbnail.MimeType="image/jpeg"><array name="ifd0"><item key="Orientation" base64="1">MQ==</item><item key="XResolution" base64="1">NzIwMDAwLzEwMDAw</item><item key="YResolution" base64="1">NzIwMDAwLzEwMDAw</item><item key="ResolutionUnit" base64="1">Mg==</item><item key="Software" base64="1">QWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKQ==</item><item key="DateTime" base64="1">MjAxNDoxMToxMCAxNzo0MDoyMw==</item><item key="Exif_IFD_Pointer" base64="1">MTY4</item></array><array name="exif"><item key="ColorSpace" base64="1">MQ==</item><item key="ExifImageWidth" base64="1">Nzcw</item><item key="ExifImageLength" base64="1">Mjgx</item></array></information></ezimage>',
            'data_type_string' => 'ezimage',
            'id' => '286',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        6 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 181,
            'contentobject_id' => 69,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => 'Create',
            'data_type_string' => 'ezstring',
            'id' => '293',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        7 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 69,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph>Increasing the productivity of your content infrastructure, eZ Publish Enterprise provides you with powerful tools to create, automate and collaborate on content...</paragraph></section>',
            'data_type_string' => 'ezxmltext',
            'id' => '295',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        8 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 69,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph>version2</paragraph></section>',
            'data_type_string' => 'ezxmltext',
            'id' => '295',
            'language_code' => 'eng-GB',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 2,
        ],
        9 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 69,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"><paragraph>version2</paragraph></section>',
            'data_type_string' => 'ezxmltext',
            'id' => '296',
            'language_code' => 'nor-NO',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 2,
        ],
        10 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 70,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml" xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom" version="5.0-variant ezpublish-1.0"><title ezxhtml:level="2">header1text</title></section>',
            'data_type_string' => 'ezrichtext',
            'id' => '297',
            'language_code' => 'nor-NO',
            'language_id' => '2',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
        11 => [
            'attribute_original_id' => 0,
            'contentclassattribute_id' => 183,
            'contentobject_id' => 70,
            'data_float' => 0,
            'data_int' => null,
            'data_text' => '<section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml" xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom" version="5.0-variant ezpublish-1.0"><title ezxhtml:level="2">header1text</title></section>',
            'data_type_string' => 'ezrichtext',
            'id' => '298',
            'language_code' => 'eng-GB',
            'language_id' => '1',
            'sort_key_int' => 0,
            'sort_key_string' => '',
            'version' => 1,
        ],
    ],
];
