<?php

return [
    'ezcontentclass' => [
        0 => [
            'always_available' => 0,
            'contentobject_name' => '<name>',
            'created' => 1024392098,
            'creator_id' => 14,
            'id' => 27,
            'identifier' => 'image',
            'initial_language_id' => 2,
            'is_container' => 0,
            'language_mask' => 3,
            'modified' => 1523277289,
            'modifier_id' => 14,
            'remote_id' => 'f6df12aa74e36230eb675f364fccd25a',
            'serialized_description_list' => 'a:1:{s:6:"eng-GB";s:0:"";}',
            'serialized_name_list' => 'a:2:{s:6:"eng-GB";s:5:"Image";s:16:"always-available";s:6:"eng-GB";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => '',
            'version' => 0,
        ],
        1 => [
            'always_available' => 0,
            'contentobject_name' => '<name>',
            'created' => 1024392098,
            'creator_id' => 14,
            'id' => 1,
            'identifier' => 'testarticle',
            'initial_language_id' => 2,
            'is_container' => 0,
            'language_mask' => 3,
            'modified' => 1523277289,
            'modifier_id' => 14,
            'remote_id' => 'f6df12aa74e36230eb675f364fccd25b',
            'serialized_description_list' => 'a:1:{s:6:"eng-GB";s:0:"";}',
            'serialized_name_list' => 'a:2:{s:6:"eng-GB";s:5:"Image";s:16:"always-available";s:6:"eng-GB";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => '',
            'version' => 0,
        ],
        2 => [
            'always_available' => 0,
            'contentobject_name' => '<name>',
            'created' => 1024392098,
            'creator_id' => 14,
            'id' => 2,
            'identifier' => 'thumbnail',
            'initial_language_id' => 2,
            'is_container' => 0,
            'language_mask' => 3,
            'modified' => 1523277289,
            'modifier_id' => 14,
            'remote_id' => 'f6df12aa74e36230eb675f364fccd25c',
            'serialized_description_list' => 'a:1:{s:6:"eng-GB";s:0:"";}',
            'serialized_name_list' => 'a:2:{s:6:"eng-GB";s:5:"Image";s:16:"always-available";s:6:"eng-GB";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => '',
            'version' => 0,
        ],
    ],
];
