parameters:
    # Default XSL stylesheets for XmlText rendering to HTML5.
    # Built-in stylesheets are treated as custom for the sake of extensibility.
    ezsettings.default.fieldtypes.ezxml.custom_xsl:
        -
            path: "%kernel.root_dir%/../vendor/ezsystems/ezplatform-xmltext-fieldtype/lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl"
            priority: 0
        -
            path: "%kernel.root_dir%/../vendor/ezsystems/ezplatform-xmltext-fieldtype/lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_custom.xsl"
            priority: 0
